// Auto-generated by scripts/generateRegistry.ts — do not edit manually
import { createElement } from 'react'
import type { RegisteredGameComponent } from '@/lib/registeredGameComponent'
import MultiCardKenoComponent from '@/components/games/multi-card-keno/MyGame'
import { myGame as MultiCardKenoConfig } from '@/components/games/multi-card-keno/myGameConfig'
import PaiGowComponent from '@/components/games/pai-gow/PaiGowGame'
import { paiGow as PaiGowConfig } from '@/components/games/pai-gow/paiGowConfig'
import HiloComponent from '@/components/games/hilo/hilo'
import { myGame as HiloConfig } from '@/components/games/hilo/hiloConfig'
import LimboComponent from '@/components/games/limbo/limbo'
import { limboGame as LimboConfig } from '@/components/games/limbo/limboConfig'
import MinesComponent from '@/components/games/mines/mines'
import { minesGame as MinesConfig } from '@/components/games/mines/minesConfig'
import ExampleGameComponent from '@/components/games/example-game/ExampleGame'
import { exampleGame as ExampleGameConfig } from '@/components/games/example-game/exampleGameConfig'
import CastAndBraceComponent from '@/components/games/cast-and-brace/MyGame'
import { myGame as CastAndBraceConfig } from '@/components/games/cast-and-brace/myGameConfig'
import FoxyShooterComponent from '@/components/games/foxy-shooter/FoxyShooter'
import { foxyShooterGame as FoxyShooterConfig } from '@/components/games/foxy-shooter/foxyShooterConfig'
import RockPaperScissorsComponent from '@/components/games/rock-paper-scissors/RPS'
import { rpsGame as RockPaperScissorsConfig } from '@/components/games/rock-paper-scissors/rpsConfig'
import JnkyzSkateOrCrashComponent from '@/components/games/jnkyz-skate-or-crash/MyGame'
import { myGame as JnkyzSkateOrCrashConfig } from '@/components/games/jnkyz-skate-or-crash/myGameConfig'
import MegaBonkComponent from '@/components/games/mega-bonk/MegaBonk'
import { megaBonk as MegaBonkConfig } from '@/components/games/mega-bonk/megaBonkConfig'
import AxeRouletteComponent from '@/components/games/axe-roulette/AxeRoulette'
import { axeRouletteGame as AxeRouletteConfig } from '@/components/games/axe-roulette/axeRouletteConfig'
import StreetLookerComponent from '@/components/games/street-looker/StreetLooker'
import { streetLooker as StreetLookerConfig } from '@/components/games/street-looker/streetLookerGameConfig'
import ChickenCrossingComponent from '@/components/games/chicken-crossing/ChickenCrossing'
import { chickenGame as ChickenCrossingConfig } from '@/components/games/chicken-crossing/chickenGameConfig'
import LootTumbleComponent from '@/components/games/loot-tumble/LootTumble'
import { lootTumbleGame as LootTumbleConfig } from '@/components/games/loot-tumble/lootTumbleConfig'
import OvertimeZombieComponent from '@/components/games/overtime-zombie/OvertimeZombie'
import { overtimeZombieGame as OvertimeZombieConfig } from '@/components/games/overtime-zombie/overtimeZombieConfig'
import SwampHopComponent from '@/components/games/swamp-hop/SwampHop'
import { swampHop as SwampHopConfig } from '@/components/games/swamp-hop/swampHopConfig'
import PageantShowdownComponent from '@/components/games/pageant-showdown/PageantShowdown'
import { pageantShowdown as PageantShowdownConfig } from '@/components/games/pageant-showdown/pageantShowdownConfig'
import LegendOfTheGoldCubComponent from '@/components/games/legend-of-the-gold-cub/MyGame'
import { goldCubGame as LegendOfTheGoldCubConfig } from '@/components/games/legend-of-the-gold-cub/myGameConfig'
import CrashOrCashOutComponent from '@/components/games/crash-or-cash-out/MyGame'
import { myGame as CrashOrCashOutConfig } from '@/components/games/crash-or-cash-out/myGameConfig'
import MinefieldPathComponent from '@/components/games/minefield-path/MyGame'
import { myGame as MinefieldPathConfig } from '@/components/games/minefield-path/myGameConfig'
import NumberDiceComponent from '@/components/games/number-dice/MyGame'
import { myGame as NumberDiceConfig } from '@/components/games/number-dice/myGameConfig'
import BlackjackComponent from '@/components/games/blackjack/MyGame'
import { myGame as BlackjackConfig } from '@/components/games/blackjack/myGameConfig'
import DeadDrawComponent from '@/components/games/dead-draw/DeadDraw'
import { deadDrawGame as DeadDrawConfig } from '@/components/games/dead-draw/deadDrawConfig'
import GemStormComponent from '@/components/games/gem-storm/Paydirt'
import { paydirt as GemStormConfig } from '@/components/games/gem-storm/paydirtConfig'

const gameRegistry: Record<string, RegisteredGameComponent> = {
  'multi-card-keno': () => createElement(MultiCardKenoComponent as RegisteredGameComponent, { game: MultiCardKenoConfig }),
  'pai-gow': () => createElement(PaiGowComponent as RegisteredGameComponent, { game: PaiGowConfig }),
  'hilo': () => createElement(HiloComponent as RegisteredGameComponent, { game: HiloConfig }),
  'limbo': () => createElement(LimboComponent as RegisteredGameComponent, { game: LimboConfig }),
  'mines': () => createElement(MinesComponent as RegisteredGameComponent, { game: MinesConfig }),
  'example-game': () => createElement(ExampleGameComponent as RegisteredGameComponent, { game: ExampleGameConfig }),
  'cast-and-brace': () => createElement(CastAndBraceComponent as RegisteredGameComponent, { game: CastAndBraceConfig }),
  'foxy-shooter': () => createElement(FoxyShooterComponent as RegisteredGameComponent, { game: FoxyShooterConfig }),
  'rock-paper-scissors': () => createElement(RockPaperScissorsComponent as RegisteredGameComponent, { game: RockPaperScissorsConfig }),
  'jnkyz-skate-or-crash': () => createElement(JnkyzSkateOrCrashComponent as RegisteredGameComponent, { game: JnkyzSkateOrCrashConfig }),
  'mega-bonk': () => createElement(MegaBonkComponent as RegisteredGameComponent, { game: MegaBonkConfig }),
  'axe-roulette': () => createElement(AxeRouletteComponent as RegisteredGameComponent, { game: AxeRouletteConfig }),
  'street-looker': () => createElement(StreetLookerComponent as RegisteredGameComponent, { game: StreetLookerConfig }),
  'chicken-crossing': () => createElement(ChickenCrossingComponent as RegisteredGameComponent, { game: ChickenCrossingConfig }),
  'loot-tumble': () => createElement(LootTumbleComponent as RegisteredGameComponent, { game: LootTumbleConfig }),
  'overtime-zombie': () => createElement(OvertimeZombieComponent as RegisteredGameComponent, { game: OvertimeZombieConfig }),
  'swamp-hop': () => createElement(SwampHopComponent as RegisteredGameComponent, { game: SwampHopConfig }),
  'pageant-showdown': () => createElement(PageantShowdownComponent as RegisteredGameComponent, { game: PageantShowdownConfig }),
  'legend-of-the-gold-cub': () => createElement(LegendOfTheGoldCubComponent as RegisteredGameComponent, { game: LegendOfTheGoldCubConfig }),
  'crash-or-cash-out': () => createElement(CrashOrCashOutComponent as RegisteredGameComponent, { game: CrashOrCashOutConfig }),
  'minefield-path': () => createElement(MinefieldPathComponent as RegisteredGameComponent, { game: MinefieldPathConfig }),
  'number-dice': () => createElement(NumberDiceComponent as RegisteredGameComponent, { game: NumberDiceConfig }),
  'blackjack': () => createElement(BlackjackComponent as RegisteredGameComponent, { game: BlackjackConfig }),
  'dead-draw': () => createElement(DeadDrawComponent as RegisteredGameComponent, { game: DeadDrawConfig }),
  'gem-storm': () => createElement(GemStormComponent as RegisteredGameComponent, { game: GemStormConfig }),
}

export { gameRegistry }
